name: soham_breath
description: A breathing app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Gerenciamento de Estado
  flutter_riverpod: ^2.6.1
  
  # Firebase (Backend e Auth)
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  
  # UI e Design
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0      # Para os gráficos
  
  # Monetização
  google_mobile_ads: ^5.0.0

  # Utilitários
  intl: ^0.19.0          # Para formatação de datas
  purchases_flutter: ^9.10.0
  purchases_ui_flutter: ^9.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
